	<li class="slide">
		<span class="handler"><img src="<?php echo UNOSLIDER_PATH; ?>public/images/handler.png" /></span>
		
		<div class="thumb-container">
			<div class="thumb-overlay">
				<a href="#" class="change-image-button">Change Image</a>
			</div>
			
			<img src="<?php echo $slide; ?>" class="thumb" >
		</div>

		<ul class="tabs editor">
			<li class="active"><a href="#tab_img_title_<?php echo $id; ?>" data-toggle="tab">Caption</a></li>
			<li><a href="#tab_img_link_<?php echo $id; ?>" data-toggle="tab">Link</a></li>
			<li><a href="#" class="open_advanced">Advanced</a></li>
		</ul>

		<div class="tab-content">
			<div class="tab-pane active" id="tab_img_title_<?php echo $id; ?>">
				<input type="text" class="caption input" name="tooltip[]" value="<?php echo stripslashes(htmlspecialchars($this->tooltips[$id])); ?>" />
			</div>

			<div class="tab-pane" id="tab_img_link_<?php echo $id; ?>">
				<div class="labeled_input">
					<label class="inset hide-if-no-js">http:// </label>
					<input type="text" class="imglink input inset " name="imglink[]" value="<?php echo $this->links['href'][$img_num]; ?>" />
					<select name="linktarget[]" class="linktarget">
						<?php 
							$targets = array('_self', '_blank', '_parent', '_top');
							foreach ($targets as $target):
						?>
							<option value="<?php echo $target; ?>" <?php selected( $this->links['target'][$img_num], $target ); ?>><?php echo $target; ?></option>
						<?php endforeach; ?>

					</select>
				</div>
			</div>

		</div>

		<input type="hidden" class="imgurl preview_item" name="slide_data[]" value="<?php echo stripslashes(htmlspecialchars($slide)); ?>" />
		<input type="hidden" class="layers" name="layers[]" value="<?php echo htmlspecialchars(json_encode($this->layers[$id])); ?>" />

		<ul class="options">
			<li><a href="#" class="remove"><img src="<?php echo UNOSLIDER_PATH; ?>public/images/cross.png" title="Remove" alt="Remove" /></a></li>
			<li><a href="#" class="clone"><img src="<?php echo UNOSLIDER_PATH; ?>public/images/clone.png" alt="Clone" title="Clone" /></a></li>
		</ul>

			<br class="clear" />
	</li>
