<div id="advanced">
	<div class="canvas">
		
	</div>
	

	<div class="colorbox-footer">
		<div class="pull-left">
			<a href="#" class="us-button-primary html_editor_preview">Preview</a>
			<a href="#" class="us-button-primary html_editor_edit">Edit</a>
		</div>
		<div class="pull-right">
			<a href="#" class="us-button-done html_editor_save">Save and Close</a>
			<a href="#" class="us-button html_editor_cancel">Cancel</a>
		</div>
	</div>
</div>