<div class="canvas preset_editor">
</div>

<div id="presets_editor">
	<div class="row">
		<div class="span10">
			<h4>Blocks</h4>
			<label for="undr_block_vertical"><dfn title="Number of blocks vertically">Vertical</dfn></label>
			
			<div class="input-append">
				<input type="text" name="undr_block_vertical" id="undr_block_vertical" class="span3" value="8" />
				<span class="add-on">blocks</span>
			</div>
			<br class="clear">
			<label for="undr_block_horizontal"><dfn title="Number of blocks horizontally">Horizontal</dfn></label>
			<div class="input-append">
				<input type="text" name="undr_block_horizontal" id="undr_block_horizontal" class="span3" value="3" />
				<span class="add-on">blocks</span>
			</div>
		</div>


		<div class="span11">
			<h4>Timing</h4>
			<label for="undr_animation_speed"><dfn title="Duration of animation">Speed</dfn></label>
			<div class="input-append">
				<input type="text" name="undr_animation_speed" id="undr_animation_speed" class="span4" value="500" />
				<span class="add-on">ms.</span>
			</div>
			<br class="clear">
			<label for="undr_animation_delay"><dfn title="Delay between blocks">Delay</dfn></label>
			<div class="input-append">
				<input type="text" name="undr_animation_delay" id="undr_animation_delay" class="span4" value="50" />
				<span class="add-on">ms.</span>
			</div>
		</div>

		<div class="span13">
			<h4>Animation</h4>
			<label for="undr_transition" class="gap"><dfn title="Type of animation applied to blocks">Transition</dfn></label>
			<select name="undr_transition" class="undr_transition" id="undr_transition">
				<?php foreach($this->transitions as $transition => $variations): ?>
				<option value="<?php print $transition; ?>"><?php print $transition; ?></option>
				<?php endforeach; ?>
			</select>
			<br class="clear">
			<label for="undr_variation" class="gap"><dfn title="Variation of selected transition">Variation</dfn></label>
			<select name="undr_variation" class="undr_variation" id="undr_variation">
				<?php foreach($this->transitions['grow'] as $variation): ?>
				<option value="<?php print $variation; ?>"><?php print $variation; ?></option>
				<?php endforeach; ?>
			</select>
		</div>
	
	
		<div class="span11">
			<h4>Direction</h4>
			<label for="undr_pattern" class="gap"><dfn title="Pattern in which transition is applied">Pattern</dfn></label>
			<select name="undr_pattern" class="undr_pattern" id="undr_pattern">
				<?php foreach($this->patterns as $pattern => $directions): ?>
				<option value="<?php print $pattern; ?>"><?php print $pattern; ?></option>
				<?php endforeach; ?>
			</select>
		
		
			<label for="undr_direction" class="gap"><dfn title="Direction modifier for pattern">Direction</dfn></label>
			<select name="undr_direction" class="undr_direction" id="undr_direction">
				<?php foreach($this->patterns['horizontal'] as $direction): ?>
				<option value="<?php print $direction; ?>"><?php print $direction; ?></option>
				<?php endforeach; ?>
			</select>
		</div>
	</div>

	<br class="clear">
	
	<input type="hidden" name="preset_id" id="preset_id" />	
	<input type="hidden" name="preset_name" id="preset_name">
</div>

<div class="colorbox-footer">
	<a href="#" class="us-button-done save_as_preset">Save as a new preset</a>
	<a href="#" class="us-button-done update_preset">Update transition</a>
	<a href="#" class="us-button cancel">Cancel</a>
</div>